/**
 * Plugin: aimage.js
 * Description: Generate gambar dengan AI
 * Command: .aimage, .aiimg, .dalle
 */

const axios = require('axios');

const handler = async (m, Obj) => {
    const { conn, q, button, text, replyAdaptive } = Obj;

    if (!text) {
        const helpText = `
╭━━━❰ *AI IMAGE GENERATOR* ❱━━━╮
┃
┃ 🎨 Generate gambar dengan AI
┃
┃ 📝 *Cara Penggunaan:*
┃
┃ .aimage <prompt>
┃ .aiimg <deskripsi>
┃
┃ *Contoh:*
┃ .aimage kucing lucu di luar angkasa
┃ .aiimg pemandangan gunung sunset
┃ .aimage anime girl cyberpunk
┃
┃ 💡 *Tips:*
┃ • Deskripsikan dengan detail
┃ • Gunakan bahasa Inggris untuk hasil terbaik
┃ • Tunggu 10-30 detik
┃
╰━━━━━━━━━━━━━━━━━━━━━━━━━━╯`;

        const buttons = [
            ...button.flow.quickReply("🐱 Kucing Lucu", ".aimage cute cat in space"),
            ...button.flow.quickReply("🏔️ Pemandangan", ".aimage mountain landscape sunset"),
            ...button.flow.quickReply("💭 AI Chat", ".ai halo")
        ];

        return replyAdaptive({
            text: helpText,
            buttons: buttons,
            title: "AI Image Generator",
            body: "Generate gambar dengan AI"
        });
    }

    try {
        await conn.sendMessage(m.chat, {
            text: "🎨 Sedang menggambar, mohon tunggu..."
        }, { quoted: q('fkontak') });

        // Call AI Image API
        const response = await axios.get(`https://api.ryzendesu.vip/api/ai/dalle?prompt=${encodeURIComponent(text)}`, {
            timeout: 60000,
            responseType: 'arraybuffer'
        });

        if (!response.data) {
            throw new Error('No image data received');
        }

        const imageBuffer = Buffer.from(response.data);

        // Send image with caption
        await conn.sendMessage(m.chat, {
            image: imageBuffer,
            caption: `
╭━━━❰ *AI IMAGE* ❱━━━╮
┃
┃ 🎨 *Prompt:* ${text}
┃
┃ ✅ Generated by AI
┃
╰━━━━━━━━━━━━━━━━━━━━━━━━━━╯`,
            contextInfo: {
                externalAdReply: {
                    title: "AI Image Generator",
                    body: "Generated successfully",
                    thumbnailUrl: global.thumbnail || "https://files.catbox.moe/5x2b8n.jpg",
                    sourceUrl: "https://wa.me/62881027174423",
                    mediaType: 1,
                    renderLargerThumbnail: true
                }
            }
        }, { quoted: q('fkontak') });

    } catch (error) {
        console.error('AI Image Error:', error);
        return replyAdaptive({
            text: `❌ *Error:* ${error.message || 'Gagal generate gambar'}\n\nSilakan coba lagi dengan prompt yang berbeda.`,
            title: "Error",
            body: "AI Image Service"
        });
    }
};

handler.command = ['aimage', 'aiimg', 'dalle', 'aiimage'];
handler.tags = ['ai'];
handler.help = ['aimage <prompt>', 'aiimg <deskripsi>'];

module.exports = handler;
